name: Docker Build, Push, Deploy, and Rollback

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Rollback image tag (empty for new deploy)'
        required: false

env:
  DOCKER_REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/lab-nextjs
  INSTANCE_NAME: lab-nextjs
  IMAGE_NAME: lab-nextjs

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag
        id: tag
        run: |
          if [ "${{ github.event.inputs.rollback_tag }}" == "" ]; then
            echo "image_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Build and Push
        if: ${{ github.event.inputs.rollback_tag == '' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.tag.outputs.image_tag }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Instance
        run: |
          ssh -i ~/.ssh/github-actions-key -o StrictHostKeyChecking=no \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{ needs.build-push.outputs.image_tag }}
          docker stop ${{ env.INSTANCE_NAME }} &> /dev/null
          docker rm ${{ env.INSTANCE_NAME }} &> /dev/null
          docker run -d \
            --name ${{ env.INSTANCE_NAME }} \
            -p 3000:3000 \
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{ needs.build-push.outputs.image_tag }}
          EOF

      - name: Update Latest Tag
        if: ${{ github.event.inputs.rollback_tag == '' }}
        run: |
          docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }} \
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
