name: Docker Build, Push, Deploy, and Rollback

on:
  push:
    branches: [master]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: lab-nextjs
  STACK_NAME: lab-nextsj-stack
  SERVICE_NAME: lab-nextsj-stack-service

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Docker Swarm
        run: |
          ssh -i ~/.ssh/github-actions-key -o StrictHostKeyChecking=no \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
            --image ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -c docker-compose.prod.yml ${{ env.STACK_NAME }}"

      - name: Verify Deployment
        run: |
          # Retry health check up to 5 times
          for i in {1..5}; do
            sleep 30
            HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.HEALTH_CHECK_URL }})
            if [ "$HEALTH_STATUS" -eq 200 ]; then
              echo "Deployment verified successfully"
              exit 0
            fi
            echo "Health check attempt $i failed"
          done
          echo "Deployment verification failed"
          exit 1

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Initiating rollback..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "docker service rollback ${{ env.SERVICE_NAME }}"

          # Verify rollback
          sleep 30
          ROLLBACK_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.HEALTH_CHECK_URL }})
          if [ "$ROLLBACK_HEALTH" -ne 200 ]; then
            echo "Rollback verification failed"
            exit 1
          fi
          echo "Rollback completed successfully"