name: "Build and deploy to server"

on:
  push:
    # Chúng ta sẽ chạy khi chúng ta release một version mới
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/lab-nextjs # Change this to your docker image name

      - name: Build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      #- name: Verify
        #run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Địa chỉ của server
          username: ${{ secrets.USERNAME }} # Username để login vào server
          key: ${{ secrets.SSH_KEY }} # Private key để login vào server

          script: |
#           Pull image về lại server
            docker pull ${{ steps.meta.outputs.tags }}
#           Xóa container cũ nếu có
            docker rm -f lab-nextjs &>/dev/null
#           Chạy container mới
            docker run -it -d --name lab-nextjs -p 3000:3000 ${{ steps.meta.outputs.tags }}